//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addresses
    {
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string Add_Type { get; set; }
        public string IsDefault { get; set; }
        public string City { get; set; }
        public decimal Pincode { get; set; }
        public string del_Address { get; set; }
    
        public virtual customers customers { get; set; }
    }
}
